### ISSUE TITLE
关于其他资源文件

### ISSUE THREAD

**Issue by size404** [nijinekoyo/GF2AssetBundleDecryption#1]
大佬关于GF2Exilium\GF2 Game\GF2_Exilium_Data\LocalCache\Data\AssetBundles_Windows\Assets\ArtsResource里的音频和CG的提取，可以再写一个程序吗，我看了您引用的git，那个项目看不懂哇。还有我发现拆出来的资源里没有剧情的文本文档，不知道云母藏哪里去了，求问大佬

**Comment by nijinekoyo** [comment]
隔壁也没写怎么解密音频资源，他只是上传了key（
我只是觉得隔壁那个执行效率有点慢，于是拿go重新搓了一份而已

**Comment by size404** [comment]
好好好感谢大佬答疑

**Comment by nijinekoyo** [comment]
我大概帮你找了一下
https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-win.zip
用这个工具可以解密音频文件，游戏密钥已经被合并进了这个项目

**Comment by nijinekoyo** [comment]
下载解压后，将音频拖到`vgmstream-cli.exe`程序上即可

**Comment by size404** [comment]
感谢您，您就是卡密sama！

**Comment by bkan1c** [comment]
您好大佬，我将awb文件音频拖到vgmstream-cli.exe程序上只出现了一句音频文件，但是将awb文件拆成众多hca文件之后再拖进去只能出现电子杂音，这是该怎么处理呢

**Comment by 66hh** [comment]
> 大佬关于GF2Exilium\GF2 Game\GF2_Exilium_Data\LocalCache\Data\AssetBundles_Windows\Assets\ArtsResource里的音频和CG的提取，可以再写一个程序吗，我看了您引用的git，那个项目看不懂哇。还有我发现拆出来的资源里没有剧情的文本文档，不知道云母藏哪里去了，求问大佬

剧情文本位于LangPackageTableCnData

**Comment by nijinekoyo** [comment]
> 您好大佬，我将awb文件音频拖到vgmstream-cli.exe程序上只出现了一句音频文件，但是将awb文件拆成众多hca文件之后再拖进去只能出现电子杂音，这是该怎么处理呢

可以发一下例子文件吗

**Comment by lasergrape** [comment]
大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。

**Comment by 66hh** [comment]
> 大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。

剧情在数据表里没加密，就是用protobuf打包了一下

**Comment by 66hh** [comment]
> 大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。

我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看

**Comment by nijinekoyo** [comment]
> > 大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。
> 
> 我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看

已经在[386f37f](https://github.com/nijinekoyo/GF2AssetBundleDecryption/commit/386f37f8b294cf4df6f2564fd2281c5730e8717e)提交中跟进剧情解析模式

**Comment by hmtime** [comment]
> > > 大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。
> > 
> > 
> > 我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看
> 
> 已经在[386f37f](https://github.com/nijinekoyo/GF2AssetBundleDecryption/commit/386f37f8b294cf4df6f2564fd2281c5730e8717e)提交中跟进剧情解析模式

你好，关于剧情文本解析模式描述的路径是否有问题呢，实际依旧是放在\Data下即可。

**Comment by lasergrape** [comment]
是的，我已发现问题，感谢您造福大伙的努力




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月7日(星期六) 晚上11:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nijinekoyo/GF2AssetBundleDecryption] 关于其他资源文件 (Issue #1)





    
大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。
  
我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看
  
已经在386f37f提交中跟进剧情解析模式
  
你好，关于剧情文本解析模式描述的路径是否有问题呢，实际依旧是放在\Data下即可。

**Comment by nijinekoyo** [comment]
> > > > 大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。
> > > 
> > > 
> > > 我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看
> > 
> > 
> > 已经在[386f37f](https://github.com/nijinekoyo/GF2AssetBundleDecryption/commit/386f37f8b294cf4df6f2564fd2281c5730e8717e)提交中跟进剧情解析模式
> 
> 你好，关于剧情文本解析模式描述的路径是否有问题呢，实际依旧是放在\Data下即可。

不是很理解，你是说游戏路径吗

**Comment by nijinekoyo** [comment]
> > > > 大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。
> > > 
> > > 
> > > 我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看
> > 
> > 
> > 已经在[386f37f](https://github.com/nijinekoyo/GF2AssetBundleDecryption/commit/386f37f8b294cf4df6f2564fd2281c5730e8717e)提交中跟进剧情解析模式
> 
> 你好，关于剧情文本解析模式描述的路径是否有问题呢，实际依旧是放在\Data下即可。

README.md写错了（
我改一下

**Comment by 66hh** [comment]
> > > > > 大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。
> > > > 
> > > > 
> > > > 我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看
> > > 
> > > 
> > > 已经在[386f37f](https://github.com/nijinekoyo/GF2AssetBundleDecryption/commit/386f37f8b294cf4df6f2564fd2281c5730e8717e)提交中跟进剧情解析模式
> > 
> > 
> > 你好，关于剧情文本解析模式描述的路径是否有问题呢，实际依旧是放在\Data下即可。
> 
> README.md写错了（ 我改一下

目前这样实际算不上剧情，只能算是文本，要给剧情对话什么的串联起来可能还需要对story的那个数据表下手，读取里面的文本id然后给串起来

**Comment by lasergrape** [comment]
好的，谢谢您






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月7日(星期六) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nijinekoyo/GF2AssetBundleDecryption] 关于其他资源文件 (Issue #1)





      
大佬好，想问一下您的解码器可以解少前2的剧情文件吗？如果可以的话麻烦您给一下解码方法或者思路吗？不是很会解剧情包加的密，如果不行的话可以请您帮忙留意下剧情包的解码器吗？十分感谢。
  
我已经上传了剧情解密器以及lua解密器，你可以去我仓库看看
  
已经在386f37f提交中跟进剧情解析模式
  
你好，关于剧情文本解析模式描述的路径是否有问题呢，实际依旧是放在\Data下即可。
  
README.md写错了（ 我改一下
  
目前这样实际算不上剧情，只能算是文本，要给剧情对话什么的串联起来可能还需要对story的那个数据表下手，读取里面的文本id然后给串起来

**Comment by 66hh** [comment]
{
            "Id": 510,
            "Chapter": 5,
            "StageGroup": 5,
            "StageId": 10510,
            "PreId": [
                509
            ],
            "Position": "4050,0",
            "Name": {
                "Id": 11036
            },
            "Icon": "icon_stagetest",
            "Code": {
                "Id": 11036
            },
            "Type": 1,
            "UnlockLevel": 27,
            "StartPoint": 2
        } 奇怪为什么story里没有剧情文本的id

**Comment by nijinekoyo** [comment]
> StageId

StageId就是对对应的剧情ID
<img width="969" alt="image" src="https://github.com/nijinekoyo/GF2AssetBundleDecryption/assets/125987288/c3413463-5726-41fa-a39d-90e0383bd407">

**Comment by nijinekoyo** [comment]
> ```
>     {
>         "Id": 510,
>         "Chapter": 5,
>         "StageGroup": 5,
>         "StageId": 10510,
>         "PreId": [
>             509
>         ],
>         "Position": "4050,0",
>         "Name": {
>             "Id": 11036
>         },
>         "Icon": "icon_stagetest",
>         "Code": {
>             "Id": 11036
>         },
>         "Type": 1,
>         "UnlockLevel": 27,
>         "StartPoint": 2
>     } 奇怪为什么story里没有剧情文本的id
> ```

有点没想明白的是`.proto`文件是怎么来的，我不是很擅长逆向（

**Comment by 66hh** [comment]
> > StageId
> 
> StageId就是对对应的剧情ID <img alt="image" width="969" src="https://user-images.githubusercontent.com/125987288/273397210-c3413463-5726-41fa-a39d-90e0383bd407.png">

但有些又查不到

**Comment by 66hh** [comment]
> > ```
> >     {
> >         "Id": 510,
> >         "Chapter": 5,
> >         "StageGroup": 5,
> >         "StageId": 10510,
> >         "PreId": [
> >             509
> >         ],
> >         "Position": "4050,0",
> >         "Name": {
> >             "Id": 11036
> >         },
> >         "Icon": "icon_stagetest",
> >         "Code": {
> >             "Id": 11036
> >         },
> >         "Type": 1,
> >         "UnlockLevel": 27,
> >         "StartPoint": 2
> >     } 奇怪为什么story里没有剧情文本的id
> > ```
> 
> 有点没想明白的是`.proto`文件是怎么来的，我不是很擅长逆向（

从dll里扣的id然后手动写的proto文件

**Comment by nijinekoyo** [comment]
> > > StageId
> > 
> > 
> > StageId就是对对应的剧情ID <img alt="image" width="969" src="https://user-images.githubusercontent.com/125987288/273397210-c3413463-5726-41fa-a39d-90e0383bd407.png">
> 
> 但有些又查不到

查不到的在游戏内有出现吗？如果没有会不会是废弃文案？

**Comment by nijinekoyo** [comment]
> > > ```
> > >     {
> > >         "Id": 510,
> > >         "Chapter": 5,
> > >         "StageGroup": 5,
> > >         "StageId": 10510,
> > >         "PreId": [
> > >             509
> > >         ],
> > >         "Position": "4050,0",
> > >         "Name": {
> > >             "Id": 11036
> > >         },
> > >         "Icon": "icon_stagetest",
> > >         "Code": {
> > >             "Id": 11036
> > >         },
> > >         "Type": 1,
> > >         "UnlockLevel": 27,
> > >         "StartPoint": 2
> > >     } 奇怪为什么story里没有剧情文本的id
> > > ```
> > 
> > 
> > 有点没想明白的是`.proto`文件是怎么来的，我不是很擅长逆向（
> 
> 从dll里扣的id然后手动写的proto文件

果然是这样吗（悲
能不能麻烦指个北，是哪个文件里面有（

**Comment by 66hh** [comment]
> > > > ```
> > > >     {
> > > >         "Id": 510,
> > > >         "Chapter": 5,
> > > >         "StageGroup": 5,
> > > >         "StageId": 10510,
> > > >         "PreId": [
> > > >             509
> > > >         ],
> > > >         "Position": "4050,0",
> > > >         "Name": {
> > > >             "Id": 11036
> > > >         },
> > > >         "Icon": "icon_stagetest",
> > > >         "Code": {
> > > >             "Id": 11036
> > > >         },
> > > >         "Type": 1,
> > > >         "UnlockLevel": 27,
> > > >         "StartPoint": 2
> > > >     } 奇怪为什么story里没有剧情文本的id
> > > > ```
> > > 
> > > 
> > > 有点没想明白的是`.proto`文件是怎么来的，我不是很擅长逆向（
> > 
> > 
> > 从dll里扣的id然后手动写的proto文件
> 
> 果然是这样吗（悲 能不能麻烦指个北，是哪个文件里面有（

其实也能做dumper去搞

**Comment by nijinekoyo** [comment]
> 其实也能做dumper去搞

global-metadata被加密了主要是，不知道怎么进行下一步

**Comment by 66hh** [comment]
> > 其实也能做dumper去搞
> 
> global-metadata被加密了主要是，不知道怎么进行下一步

我已经搞完了，我给目前解出来的数据表都丢这里了
https://github.com/66hh/GF2ExiliumData

**Comment by 66hh** [comment]
> > 其实也能做dumper去搞
> 
> global-metadata被加密了主要是，不知道怎么进行下一步

这玩意就个传统加密分分钟就凎开了

**Comment by nijinekoyo** [comment]
> > > 其实也能做dumper去搞
> > 
> > 
> > global-metadata被加密了主要是，不知道怎么进行下一步
> 
> 这玩意就个传统加密分分钟就凎开了

细说（

**Comment by nijinekoyo** [comment]
> > > 其实也能做dumper去搞
> > 
> > 
> > global-metadata被加密了主要是，不知道怎么进行下一步
> 
> 这玩意就个传统加密分分钟就凎开了

呃啊还是没搞明白（悲

**Comment by UNKNOW894** [comment]
> 您好大佬，我将awb文件音频拖到vgmstream-cli.exe程序上只出现了一句音频文件，但是将awb文件拆成众多hca文件之后再拖进去只能出现电子杂音，这是该怎么处理呢



破案了 单独拖动单个文件是无法解包单个文件内的所有对话的，必须同时将同名的ACB、AWB文件放在同一个文件夹下然后新建一个waves文件夹然后在CMD命令指示符下按照这个方法才能开始解包

1.CD你需要解包的ACB和AWB所在文件夹（ACB和AWB必须存在于同一文件夹内） 如 CD D:\少前2音频文件，然后敲D:，回车

然后抄这条命令：for /f %I in ('dir %CD%\*.awb  /A-D /B /S /ON') do D:\（vgmstream-releases坐在位置文件夹）\vgmstream-cli.exe -S 0 -o D:\少前2音频文件\waves\?f-?n.wav %~nxI
这是我和我朋友研究如何解包这个破AWB ACB小四个月的成果（期间包括了双方上班忙碌等导致的失联情况）

**Comment by df404-45** [comment]
大佬您好，我用VGMToolbox解CG动画，同时解出HCA音频，再通过vgmstream转换为wav文件，但是wav文件没有声音是怎么回事，求解答

**Comment by df404-45** [comment]
大佬您好，我用VGMToolbox解CG动画，同时解出HCA，再通过vgmstream大佬转换为wav文件，但是wav文件没有声音是怎么回事，求解答

**Comment by UNKNOW894** [comment]
需要把hca再解包

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by UNKNOW894** [comment]
具体的方法我不确定，但是这里有思路https://www.52pojie.cn/thread-1874512-1-1.html

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by InkYard** [comment]
> > 您好大佬，我将awb文件音频拖到vgmstream-cli.exe程序上只出现了一句音频文件，但是将awb文件拆成众多hca文件之后再拖进去只能出现电子杂音，这是该怎么处理呢
> 
> 破案了 单独拖动单个文件是无法解包单个文件内的所有对话的，必须同时将同名的ACB、AWB文件放在同一个文件夹下，然后新建一个waves文件夹，然后在CMD命令指示符下按照这个方法才能开始解包
> 
> 1.CD 你需要解包的ACB和AWB所在文件夹（ACB和AWB必须存在于同一文件夹内） 如 CD D：\少前2音频文件，然后敲D：，回车
> 
> 然后抄这条命令：for /f %I in （'dir %CD%*.awb /A-D /B /S /ON'） DO D：\（vgmstream-releases坐在位置文件夹）\vgmstream-cli.exe -S 0 -o D：\少前2音频文件\waves？f-？n.wav %~nxI 这是我和我朋友研究如何解包这个破AWB ACB小四个月的成果（期间包括了双方上班忙碌等导致的失联情况）

大佬您好，我想请问一下按照您给的命令最终会出现file GF2 not found的情况，这是为什么

**Comment by df404-45** [comment]
> 需要把hca再解包获取Outlook for Android< https://aka.ms/AAb9ysg >
> […](#)

video/pc/gunget  只有这个文件夹里usm转m2v配套的adx文件用vgmstream去转wav文件是没有声音的。其他文件夹的adx转wav都是有声音的，这是正常的吗？
