### ISSUE TITLE
关于生成后的json内容乱序

### ISSUE THREAD

**Issue by size404** [nijinekoyo/GF2AssetBundleDecryption#2]
已解决，可以通过python重排
import json
import pandas as pd

input_file_name = "LangPackageTableCnData.json" 
output_file_name = "sorted_data.json"  

with open(input_file_name, "r", encoding="utf-8") as input_file:
    json_data = json.load(input_file)
df = pd.DataFrame(json_data["Data"])
sorted_df = df.sort_values(by="Id")
sorted_df.to_json(output_file_name, orient="records", force_ascii=False, indent=4)

print(f"已生成排序后的 JSON 文件: {output_file_name}")

**Comment by nijinekoyo** [comment]
剧情文本似乎是有另外的文件进行排序的
