### ISSUE TITLE
关于最近更新的文件

### ISSUE THREAD

**Issue by size404** [nijinekoyo/GF2AssetBundleDecryption#3]
大佬您好，昨天更新的文件中table文件夹更新了不少新内容，但是您的程序只能够解读其中的两个文件，请问如果想要解读更多的文件，应该怎么做，谢谢大佬

**Comment by size404** [comment]
希望能在table中的其他文件中找到有关剧情文本调用的蛛丝马迹，尽管里面不存在中文，谢谢

**Comment by nijinekoyo** [comment]
关于文本文件的解包我目前还没有进展，Protobuf的解析需要结构，但是我还没有去探索MetaData的解密方法，最近也比较忙，这个项目想等12月21日正式上线后再推进

**Comment by size404** [comment]
好的明白了，感谢大佬

**Comment by XDcedar** [comment]
请问最近更新的文件里，为何不同的人解密得到的Id不一样？同一句剧情对话，这台电脑上下载解出来拿到的Id和在另一台电脑下载解出来拿到的Id不同，不知道为什么，难道这个Id跟账号有关？

**Comment by nijinekoyo** [comment]
> 请问最近更新的文件里，为何不同的人解密得到的Id不一样？同一句剧情对话，这台电脑上下载解出来拿到的Id和在另一台电脑下载解出来拿到的Id不同，不知道为什么，难道这个Id很账号有关？

这就得反编译il2Cpp看了，可能是存在某种算法

**Comment by XDcedar** [comment]
> 这就得反编译il2Cpp看了，可能是存在某种算法

主要是有传言说可以通过这个Id的差异来反追踪解包者，但我看Id位数这么短，不太可能定位到玩家才对..现在搞不明白状况..

**Comment by nijinekoyo** [comment]
> > 这就得反编译il2Cpp看了，可能是存在某种算法
> 
> 主要是有传言说可以通过这个Id的差异来反追踪解包者，但我看Id位数这么短，不太可能定位到玩家才对..现在搞不明白状况..

wow，那可以问问@66hh 大佬

**Comment by XDcedar** [comment]
> > > 这就得反编译il2Cpp看了，可能是存在某种算法
> > 
> > 主要是有传言说可以通过这个Id的差异来反追踪解包者，但我看Id位数这么短，不太可能定位到玩家才对..现在搞不明白状况..
> 
> wow，那可以问问@66hh 大佬

我之前跟人比对过原始的 `LangPackageTableCnBuiltinData.bytes` 和 `LangPackageTableCnData.bytes` 的哈希，结果是 `LangPackageTableCnBuiltinData.bytes` 这个比较小的文件的哈希是相同的，但是 `LangPackageTableCnData.bytes` 这个大文件的哈希不相同。用一个文件多次解包的 Id 不会变化，但不同玩家解出来的 Id 好像全都不同（目前没见到过 Id 相同的数据）。有人认为是版本不同，但我按理来说大家同一时间更新的，版本不可能不同才对
我就只知道这么多了，求 @66hh 大佬解答（

**Comment by size404** [comment]
就我所知那天晚上发生了不止一次版本更新，是不是文件本身就有不同？

**Comment by XDcedar** [comment]
> 就我所知那天晚上发生了不止一次版本更新，是不是文件本身就有不同？

我是16号10点左右更新的，不是15号晚上。这时版本应该稳定了才对。
如果只是版本不同，那按理来说无论如何都应该有人的Id相同才对，然而我见到过好几张截图，都跟我的Id不同，相互之间好像也不同。

**Comment by 66hh** [comment]
> > 就我所知那天晚上发生了不止一次版本更新，是不是文件本身就有不同？
> 
> 我是16号10点左右更新的，不是15号晚上。这时版本应该稳定了才对。 如果只是版本不同，那按理来说无论如何都应该有人的Id相同才对，然而我见到过好几张截图，都跟我的Id不同，相互之间好像也不同。

感觉不太可能是用来追踪的，毕竟这个文件不用登录也能下

**Comment by 66hh** [comment]
> > > 就我所知那天晚上发生了不止一次版本更新，是不是文件本身就有不同？
> > 
> > 
> > 我是16号10点左右更新的，不是15号晚上。这时版本应该稳定了才对。 如果只是版本不同，那按理来说无论如何都应该有人的Id相同才对，然而我见到过好几张截图，都跟我的Id不同，相互之间好像也不同。
> 
> 感觉不太可能是用来追踪的，毕竟这个文件不用登录也能下

而且按理来说这个里面的id只是作为index使用的，人要是给indexmap了他这也追踪不出来啊

**Comment by XDcedar** [comment]
> 感觉不太可能是用来追踪的，毕竟这个文件不用登录也能下

> 而且按理来说这个里面的id只是作为index使用的，人要是给indexmap了他这也追踪不出来啊

感觉很有道理..如果不是拿来追踪的，那就不管那么多了，就当一个未解之谜吧（

**Comment by daxigua36** [comment]
@XDcedar @66hh @size404 大家好大佬
你们还继续进展这个项目吗？
我可以提供帮助

**Comment by nijinekoyo** [comment]
> @XDcedar @66hh @size404 大家好大佬 你们还继续进展这个项目吗？ 我可以提供帮助

加密方式出现变化了吗？
