### ISSUE TITLE
剧情文本解析模式输出不全

### ISSUE THREAD

**Issue by chesha1** [nijinekoyo/GF2AssetBundleDecryption#4]
下载 exe 文件并放到指定文件夹后，在控制台输入
```shell
.\GF2AssetBundleDecryption_Windows_x86_64.exe -model story -table_path './Table'
```
输出：
```
panic: open '.\Table'\LangPackageTableCnBuiltinData.bytes: The system cannot find the path specified.

goroutine 1 [running]:
main.main()
        D:/Dev/golang/GF2AssetBundleDecryption/main.go:97 +0x5ed
```
然后再在控制台输入
```shell
.\GF2AssetBundleDecryption_Windows_x86_64.exe -model story -table_path ./Table
```
这次输出
```
解析成功，文件已保存至: table_decrypted_output\LangPackageTableCnBuiltinData.json
解析成功，文件已保存至: table_decrypted_output\LangPackageTableCnData.json
```
看上去 Table 文件夹里有好多 .bytes 文件，但是最后只解析出 2 个文件，这个是正常现象吗？

**Comment by nijinekoyo** [comment]
是的，目前只做了这两个文件的解析，其他文件的结构没有去抠出来

**Comment by chesha1** [comment]
> 是的，目前只做了这两个文件的解析，其他文件的结构没有去抠出来

好的大佬，顺便再请教一个问题，请问人形的基础数据在哪里可以看到，在 Table 这个目录里吗？
在 https://github.com/66hh/GF2ExiliumData 里有之前版本的 Table 目录得到完整数据，但是搜索了一下没找到

**Comment by nijinekoyo** [comment]
> > 是的，目前只做了这两个文件的解析，其他文件的结构没有去抠出来
> 
> 好的大佬，顺便再请教一个问题，请问人形的基础数据在哪里可以看到，在 Table 这个目录里吗？ 在 https://github.com/66hh/GF2ExiliumData 里有之前版本的 Table 目录得到完整数据，但是搜索了一下没找到

抱歉，这个还真不清楚
